[package]
name = "pixelflut"
version = "0.1.0"
publish = false
authors = ["Finn-Thorben Sell <dev@finn-thorben.me>"]
edition = "2021"
description = "pixel drawing game for programmers inspired by reddits r/place"
documentation = "https://docs.rs/pixelflut"
readme = "README.md"
repository = "https://github.com/ftsell/pixelflut.git"
license = "MIT"
keywords = ["pixelflut"]
categories = ["command-line-utilities", "games"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cli = ["clap", "pretty_env_logger"]

[profile.release]
lto = true

[profile.bench]
debug = true

[profile.dev]
opt-level = 2

[lib]
path = "src/lib.rs"

[[bin]]
name = "pixelflut"
path = "src/main.rs"
required-features = ["cli"]

[[bench]]
name = "pixmap_benchmark"
harness = false

[[bench]]
name = "live_server_benchmark"
harness = false

[dependencies]
anyhow = "1.0.68"
base64 = "0.20.0"
byteorder = "1.4.3"
bytes = "1.3.0"
clap = { version = "4.0.30", optional = true, features = [ "derive" ] }
futures-util = "0.3.25"
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.1"
pretty_env_logger = { version = "0.4.0", optional = true }
regex = "1.7.0"
sha1 = "0.10.5"
thiserror = "1.0.38"
tokio = { version = "1.24.2", features = ["full"] }
tokio-tungstenite = "0.18.0"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }
quickcheck = "0.9.2"
tempfile = "3.3.0"
